//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.turbine.com/SE/AMS", ConfigurationName="WbAuthenticationSoap")]
public interface WbAuthenticationSoap
{
    
    // CODEGEN: Generating message contract since element name consoleTicket from namespace http://www.turbine.com/SE/AMS is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://www.turbine.com/SE/AMS/AuthenticateWbid", ReplyAction="*")]
    AuthenticateWbidResponse AuthenticateWbid(AuthenticateWbidRequest request);
    
    // CODEGEN: Generating message contract since element name consoleTicket from namespace http://www.turbine.com/SE/AMS is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://www.turbine.com/SE/AMS/AuthenticateViaConsole", ReplyAction="*")]
    AuthenticateViaConsoleResponse AuthenticateViaConsole(AuthenticateViaConsoleRequest request);
    
    // CODEGEN: Generating message contract since element name consoleTicket from namespace http://www.turbine.com/SE/AMS is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://www.turbine.com/SE/AMS/AuthenticateAndAssociate", ReplyAction="*")]
    AuthenticateAndAssociateResponse AuthenticateAndAssociate(AuthenticateAndAssociateRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class AuthenticateWbidRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateWbid", Namespace="http://www.turbine.com/SE/AMS", Order=0)]
    public AuthenticateWbidRequestBody Body;
    
    public AuthenticateWbidRequest()
    {
    }
    
    public AuthenticateWbidRequest(AuthenticateWbidRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.turbine.com/SE/AMS")]
public partial class AuthenticateWbidRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string consoleTicket;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string realm;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string consoleId;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string wbEmail;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string password;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
    public string title;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
    public string uniqueId;
    
    public AuthenticateWbidRequestBody()
    {
    }
    
    public AuthenticateWbidRequestBody(string consoleTicket, string realm, string consoleId, string wbEmail, string password, string title, string uniqueId)
    {
        this.consoleTicket = consoleTicket;
        this.realm = realm;
        this.consoleId = consoleId;
        this.wbEmail = wbEmail;
        this.password = password;
        this.title = title;
        this.uniqueId = uniqueId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class AuthenticateWbidResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateWbidResponse", Namespace="http://www.turbine.com/SE/AMS", Order=0)]
    public AuthenticateWbidResponseBody Body;
    
    public AuthenticateWbidResponse()
    {
    }
    
    public AuthenticateWbidResponse(AuthenticateWbidResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.turbine.com/SE/AMS")]
public partial class AuthenticateWbidResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string AuthenticateWbidResult;
    
    public AuthenticateWbidResponseBody()
    {
    }
    
    public AuthenticateWbidResponseBody(string AuthenticateWbidResult)
    {
        this.AuthenticateWbidResult = AuthenticateWbidResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class AuthenticateViaConsoleRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateViaConsole", Namespace="http://www.turbine.com/SE/AMS", Order=0)]
    public AuthenticateViaConsoleRequestBody Body;
    
    public AuthenticateViaConsoleRequest()
    {
    }
    
    public AuthenticateViaConsoleRequest(AuthenticateViaConsoleRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.turbine.com/SE/AMS")]
public partial class AuthenticateViaConsoleRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string consoleTicket;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string realm;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string consoleId;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string password;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string title;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
    public string uniqueId;
    
    public AuthenticateViaConsoleRequestBody()
    {
    }
    
    public AuthenticateViaConsoleRequestBody(string consoleTicket, string realm, string consoleId, string password, string title, string uniqueId)
    {
        this.consoleTicket = consoleTicket;
        this.realm = realm;
        this.consoleId = consoleId;
        this.password = password;
        this.title = title;
        this.uniqueId = uniqueId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class AuthenticateViaConsoleResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateViaConsoleResponse", Namespace="http://www.turbine.com/SE/AMS", Order=0)]
    public AuthenticateViaConsoleResponseBody Body;
    
    public AuthenticateViaConsoleResponse()
    {
    }
    
    public AuthenticateViaConsoleResponse(AuthenticateViaConsoleResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.turbine.com/SE/AMS")]
public partial class AuthenticateViaConsoleResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string AuthenticateViaConsoleResult;
    
    public AuthenticateViaConsoleResponseBody()
    {
    }
    
    public AuthenticateViaConsoleResponseBody(string AuthenticateViaConsoleResult)
    {
        this.AuthenticateViaConsoleResult = AuthenticateViaConsoleResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class AuthenticateAndAssociateRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateAndAssociate", Namespace="http://www.turbine.com/SE/AMS", Order=0)]
    public AuthenticateAndAssociateRequestBody Body;
    
    public AuthenticateAndAssociateRequest()
    {
    }
    
    public AuthenticateAndAssociateRequest(AuthenticateAndAssociateRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.turbine.com/SE/AMS")]
public partial class AuthenticateAndAssociateRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string consoleTicket;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string realm;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string consoleId;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string wbEmail;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string password;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
    public string title;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
    public string uniqueId;
    
    public AuthenticateAndAssociateRequestBody()
    {
    }
    
    public AuthenticateAndAssociateRequestBody(string consoleTicket, string realm, string consoleId, string wbEmail, string password, string title, string uniqueId)
    {
        this.consoleTicket = consoleTicket;
        this.realm = realm;
        this.consoleId = consoleId;
        this.wbEmail = wbEmail;
        this.password = password;
        this.title = title;
        this.uniqueId = uniqueId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class AuthenticateAndAssociateResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateAndAssociateResponse", Namespace="http://www.turbine.com/SE/AMS", Order=0)]
    public AuthenticateAndAssociateResponseBody Body;
    
    public AuthenticateAndAssociateResponse()
    {
    }
    
    public AuthenticateAndAssociateResponse(AuthenticateAndAssociateResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.turbine.com/SE/AMS")]
public partial class AuthenticateAndAssociateResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string AuthenticateAndAssociateResult;
    
    public AuthenticateAndAssociateResponseBody()
    {
    }
    
    public AuthenticateAndAssociateResponseBody(string AuthenticateAndAssociateResult)
    {
        this.AuthenticateAndAssociateResult = AuthenticateAndAssociateResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface WbAuthenticationSoapChannel : WbAuthenticationSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WbAuthenticationSoapClient : System.ServiceModel.ClientBase<WbAuthenticationSoap>, WbAuthenticationSoap
{
    
    public WbAuthenticationSoapClient()
    {
    }
    
    public WbAuthenticationSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WbAuthenticationSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WbAuthenticationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WbAuthenticationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    AuthenticateWbidResponse WbAuthenticationSoap.AuthenticateWbid(AuthenticateWbidRequest request)
    {
        return base.Channel.AuthenticateWbid(request);
    }
    
    public string AuthenticateWbid(string consoleTicket, string realm, string consoleId, string wbEmail, string password, string title, string uniqueId)
    {
        AuthenticateWbidRequest inValue = new AuthenticateWbidRequest();
        inValue.Body = new AuthenticateWbidRequestBody();
        inValue.Body.consoleTicket = consoleTicket;
        inValue.Body.realm = realm;
        inValue.Body.consoleId = consoleId;
        inValue.Body.wbEmail = wbEmail;
        inValue.Body.password = password;
        inValue.Body.title = title;
        inValue.Body.uniqueId = uniqueId;
        AuthenticateWbidResponse retVal = ((WbAuthenticationSoap)(this)).AuthenticateWbid(inValue);
        return retVal.Body.AuthenticateWbidResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    AuthenticateViaConsoleResponse WbAuthenticationSoap.AuthenticateViaConsole(AuthenticateViaConsoleRequest request)
    {
        return base.Channel.AuthenticateViaConsole(request);
    }
    
    public string AuthenticateViaConsole(string consoleTicket, string realm, string consoleId, string password, string title, string uniqueId)
    {
        AuthenticateViaConsoleRequest inValue = new AuthenticateViaConsoleRequest();
        inValue.Body = new AuthenticateViaConsoleRequestBody();
        inValue.Body.consoleTicket = consoleTicket;
        inValue.Body.realm = realm;
        inValue.Body.consoleId = consoleId;
        inValue.Body.password = password;
        inValue.Body.title = title;
        inValue.Body.uniqueId = uniqueId;
        AuthenticateViaConsoleResponse retVal = ((WbAuthenticationSoap)(this)).AuthenticateViaConsole(inValue);
        return retVal.Body.AuthenticateViaConsoleResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    AuthenticateAndAssociateResponse WbAuthenticationSoap.AuthenticateAndAssociate(AuthenticateAndAssociateRequest request)
    {
        return base.Channel.AuthenticateAndAssociate(request);
    }
    
    public string AuthenticateAndAssociate(string consoleTicket, string realm, string consoleId, string wbEmail, string password, string title, string uniqueId)
    {
        AuthenticateAndAssociateRequest inValue = new AuthenticateAndAssociateRequest();
        inValue.Body = new AuthenticateAndAssociateRequestBody();
        inValue.Body.consoleTicket = consoleTicket;
        inValue.Body.realm = realm;
        inValue.Body.consoleId = consoleId;
        inValue.Body.wbEmail = wbEmail;
        inValue.Body.password = password;
        inValue.Body.title = title;
        inValue.Body.uniqueId = uniqueId;
        AuthenticateAndAssociateResponse retVal = ((WbAuthenticationSoap)(this)).AuthenticateAndAssociate(inValue);
        return retVal.Body.AuthenticateAndAssociateResult;
    }
}
